### ISSUE TITLE
Japanese text wrapping in chart option pane

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-samples-src#24] opened 2017-03-16 11:13 UTC
Go here

![image](https://cloud.githubusercontent.com/assets/9548226/23993699/42365fd6-0a4a-11e7-96cc-2ca0d9170f1a.png)
https://igniteui.github.io/help-samples/16.2/JA/data-chart/series-highlighting/index.html

The text should not be wrapped

**Comment by damyanpetev** [comment] 2019-10-01 08:41
This seems to be resolved either in the sample or the components, but can't reproduce it anymore in 16.2 or latest 19.1. Closing.

**Closed as completed by damyanpetev** 2019-10-01 08:41 UTC
Labels: bug
