### ISSUE TITLE
Tooltips in English for JP grid sample

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-samples-src#23] opened 2017-03-14 12:20 UTC
Go here
https://igniteui.github.io/help-samples/16.2/JA/grid/tooltips/index.html

Hover over the date column

![image](https://cloud.githubusercontent.com/assets/9548226/23900317/54058b9a-08c1-11e7-8d9c-2e6cb55a7029.png)

**Comment by damyanpetev** [comment] 2017-04-06 12:52
Actually not sure if this is a bug - the tooltips represent the data (that one doesn't have a Japanese version) so everything is sort of expected to be in English. That is, except the date column using JavaScript Date and its string representation is actually dependent on the browser language (I see English tooltip on the JA sample for example).
@mpavlinov Seeing this behavior perhaps the Date column shouldn't have tooltips enabled?

**Comment by mpavlinov** [comment] 2019-02-18 07:32
@EmilTanev What Damyan says is correct.
@damyanpetev I don't think we should disable tooltips for the Date column.
Closing this one as "By Design".

**Closed as completed by mpavlinov** 2019-02-18 07:32 UTC
Labels: bug, wontfix
